import fs from 'node:fs/promises';
import path from 'node:path';
import { generateSite } from '../src/generator.js';

const tempOut = path.resolve('.tmp-smoke-dist');
await generateSite([path.resolve('.')], tempOut, {
  description: 'Static site generator for browsing git repositories.',
  categories: ['tools', 'documentation']
});

const slug = 'ithildin';

const required = [
  path.join(tempOut, 'index.html'),
  path.join(tempOut, 'manifest.schema.json'),
  path.join(tempOut, slug, 'index.html'),
  path.join(tempOut, slug, 'metadata.json'),
  path.join(tempOut, 'assets', 'site.css'),
  path.join(tempOut, 'assets', 'alpine.min.js'),
  path.join(tempOut, 'assets', 'themes', 'parchment.css'),
  path.join(tempOut, 'assets', 'themes', 'obsidian.css'),
  path.join(tempOut, 'assets', 'themes', 'arctic.css'),
  path.join(tempOut, 'assets', 'themes', 'ember.css'),
  path.join(tempOut, 'assets', 'themes', 'terminal.css'),
  path.join(tempOut, slug, 'files', 'src--cli.js.html'),
  path.join(tempOut, slug, 'files', 'src--generator.js.html')
];

let failed = false;

for (const file of required) {
  try {
    await fs.access(file);
  } catch {
    console.error(`MISSING: ${path.relative(tempOut, file)}`);
    failed = true;
  }
}

// Verify a file page has correct asset links
const samplePage = await fs.readFile(
  path.join(tempOut, slug, 'files', 'src--cli.js.html'),
  'utf8'
);

if (!samplePage.includes('../../assets/site.css')) {
  console.error('FAIL: asset link to site.css not found in file page');
  failed = true;
}

if (!samplePage.includes('../../assets/alpine.min.js')) {
  console.error('FAIL: asset link to alpine.min.js not found in file page');
  failed = true;
}

if (!samplePage.includes('Generated by')) {
  console.error('FAIL: footer missing from file page');
  failed = true;
}

if (!samplePage.includes('Repositories')) {
  console.error('FAIL: breadcrumb missing from file page');
  failed = true;
}

if (!samplePage.includes('theme-switcher')) {
  console.error('FAIL: theme switcher missing from file page');
  failed = true;
}

// Verify root index fetches the manifest and links to the schema
const globalIndex = await fs.readFile(path.join(tempOut, 'index.html'), 'utf8');
if (!globalIndex.includes("fetch('manifest.json')")) {
  console.error('FAIL: root index does not fetch manifest.json');
  failed = true;
}

if (!globalIndex.includes('./manifest.schema.json')) {
  console.error('FAIL: root index missing manifest schema link');
  failed = true;
}

if (!globalIndex.includes('No repositories found.')) {
  console.error('FAIL: root index missing empty state message');
  failed = true;
}

if (!globalIndex.includes('Generated by')) {
  console.error('FAIL: footer missing from root index');
  failed = true;
}

// Verify repo index links to file pages
const repoIndex = await fs.readFile(path.join(tempOut, slug, 'index.html'), 'utf8');
if (!repoIndex.includes('./files/')) {
  console.error('FAIL: repo index missing file links');
  failed = true;
}

if (!repoIndex.includes('Repositories')) {
  console.error('FAIL: breadcrumb missing from repo index');
  failed = true;
}

const metadata = JSON.parse(await fs.readFile(path.join(tempOut, slug, 'metadata.json'), 'utf8'));
if (metadata.description !== 'Static site generator for browsing git repositories.') {
  console.error('FAIL: metadata.json missing description');
  failed = true;
}

if (!Array.isArray(metadata.categories) || metadata.categories.join(',') !== 'documentation,tools') {
  console.error('FAIL: metadata.json missing categories');
  failed = true;
}

await fs.rm(tempOut, { recursive: true, force: true });

if (failed) {
  process.exit(1);
}

console.log('smoke test passed');
