import { escapeHtml } from './utils.js';

const LOGO_FULL = `<svg class="logo-mark" width="60" height="70" viewBox="0 0 120 140" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
  <path d="M20 130 L20 55 Q20 20 60 8 Q100 20 100 55 L100 130"/>
  <path d="M30 130 L30 58 Q30 28 60 18 Q90 28 90 58 L90 130" opacity="0.4"/>
  <line x1="20" y1="130" x2="100" y2="130"/>
  <g transform="translate(60,8)"><line x1="0" y1="-9" x2="0" y2="9"/><line x1="-9" y1="0" x2="9" y2="0"/><line x1="-6" y1="-6" x2="6" y2="6"/><line x1="6" y1="-6" x2="-6" y2="6"/><circle cx="0" cy="0" r="2" fill="currentColor" stroke="none"/></g>
  <g opacity="0.85"><path d="M36 130 L36 70"/><path d="M36 95 Q28 88 24 78"/><path d="M36 85 Q30 78 27 68"/><path d="M36 75 Q32 68 30 58"/><path d="M36 95 Q42 90 44 84"/><path d="M36 80 Q41 76 43 70"/><path d="M36 130 Q30 126 26 130"/><path d="M36 130 Q32 124 28 126"/></g>
  <g opacity="0.85"><path d="M84 130 L84 70"/><path d="M84 95 Q92 88 96 78"/><path d="M84 85 Q90 78 93 68"/><path d="M84 75 Q88 68 90 58"/><path d="M84 95 Q78 90 76 84"/><path d="M84 80 Q79 76 77 70"/><path d="M84 130 Q90 126 94 130"/><path d="M84 130 Q88 124 92 126"/></g>
  <g stroke-width="2.2"><line x1="60" y1="42" x2="60" y2="118"/><line x1="52" y1="42" x2="68" y2="42"/><line x1="52" y1="118" x2="68" y2="118"/></g>
  <g opacity="0.5"><circle cx="28" cy="42" r="1.5" fill="currentColor" stroke="none"/><line x1="28" y1="38" x2="28" y2="46" stroke-width="1"/><line x1="24" y1="42" x2="32" y2="42" stroke-width="1"/><circle cx="92" cy="42" r="1.5" fill="currentColor" stroke="none"/><line x1="92" y1="38" x2="92" y2="46" stroke-width="1"/><line x1="88" y1="42" x2="96" y2="42" stroke-width="1"/></g>
  <g fill="currentColor" stroke="none" opacity="0.3"><circle cx="38" cy="32" r="1"/><circle cx="46" cy="23" r="1"/><circle cx="54" cy="18" r="1"/><circle cx="66" cy="18" r="1"/><circle cx="74" cy="23" r="1"/><circle cx="82" cy="32" r="1"/></g>
</svg>`;

const LOGO_SMALL = `<svg class="logo-mark-sm" width="20" height="24" viewBox="0 0 120 140" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
  <path d="M20 130 L20 55 Q20 20 60 8 Q100 20 100 55 L100 130"/>
  <line x1="20" y1="130" x2="100" y2="130"/>
  <g transform="translate(60,8)"><line x1="0" y1="-9" x2="0" y2="9"/><line x1="-9" y1="0" x2="9" y2="0"/><circle cx="0" cy="0" r="3" fill="currentColor" stroke="none"/></g>
  <g stroke-width="3.5"><line x1="60" y1="42" x2="60" y2="118"/><line x1="50" y1="42" x2="70" y2="42"/><line x1="50" y1="118" x2="70" y2="118"/></g>
</svg>`;

function renderBreadcrumbs(items) {
  const crumbs = items
    .map((item, index) => {
      const separator = index === 0 ? '' : '<span class="sep">/</span>';
      const label = escapeHtml(item.label);
      const content = item.href
        ? `<a href="${escapeHtml(item.href)}">${label}</a>`
        : `<span>${label}</span>`;

      return `${separator}<li>${content}</li>`;
    })
    .join('');

  return `<nav aria-label="Breadcrumb"><ol class="breadcrumb">${crumbs}</ol></nav>`;
}

function renderThemeHeadScript(defaultTheme, assetsPath) {
  return `<script>
      (function() {
        var saved = localStorage.getItem('ithildin-theme');
        if (saved && saved !== '${defaultTheme}') {
          document.write('<link rel="stylesheet" href="${assetsPath}/themes/' + saved + '.css" />');
        } else {
          document.write('<link rel="stylesheet" href="${assetsPath}/site.css" />');
        }
      })();
    </script>
    <noscript><link rel="stylesheet" href="${assetsPath}/site.css" /></noscript>`;
}

function renderThemeSwitcher(themes, defaultTheme, assetsPath) {
  const options = themes.map((t) => `<option value="${t}">${t[0].toUpperCase() + t.slice(1)}</option>`).join('');
  return `<select class="theme-switcher" aria-label="Theme">${options}</select>
    <script>
      (function() {
        var sel = document.querySelector('.theme-switcher');
        var link = document.querySelector('link[rel="stylesheet"]');
        var base = '${assetsPath}/themes/';
        var saved = localStorage.getItem('ithildin-theme') || '${defaultTheme}';
        sel.value = saved;
        sel.addEventListener('change', function() {
          link.href = base + sel.value + '.css';
          localStorage.setItem('ithildin-theme', sel.value);
        });
      })();
    </script>`;
}

function renderFooter() {
  return `<footer class="footer">
    Generated by <a href="https://github.com/boblangley/ithildin">Ithildin</a>
  </footer>`;
}

export function pageShell({ title, sidebar, content, rootPath = '..', breadcrumbs = [], description = '', themes = [], defaultTheme = '' }) {
  const assetsPath = `${rootPath}/assets`;
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>${escapeHtml(title)} | Ithildin</title>
    ${themes.length > 0 ? renderThemeHeadScript(defaultTheme, assetsPath) : `<link rel="stylesheet" href="${assetsPath}/site.css" />`}
    <script defer src="${assetsPath}/alpine.min.js"></script>
  </head>
  <body>
    <div class="viewer-page">
      <header class="viewer-header">
        <a class="viewer-brand" href="${rootPath}/index.html">
          ${LOGO_SMALL}
          Ithildin
        </a>
        <div class="viewer-header-right">
          ${renderBreadcrumbs(breadcrumbs)}
          ${themes.length > 0 ? renderThemeSwitcher(themes, defaultTheme, assetsPath) : ''}
        </div>
      </header>${description ? `\n      <p class="repo-description">${escapeHtml(description)}</p>` : ''}
      <div class="viewer-layout">
        <aside class="sidebar">
          <div class="sidebar-title">Files</div>
          <ul class="file-tree">${sidebar}</ul>
        </aside>
        <main class="main-content">
          ${content}
        </main>
      </div>
      ${renderFooter()}
    </div>
  </body>
</html>`;
}

export function rootIndexPage({ themes = [], defaultTheme = '' } = {}) {
  const assetsPath = './assets';
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>Repositories | Ithildin</title>
    ${themes.length > 0 ? renderThemeHeadScript(defaultTheme, assetsPath) : `<link rel="stylesheet" href="${assetsPath}/site.css" />`}
  </head>
  <body>
    <div class="index-page">
      <header class="index-header">
        <div class="logo-group">
          ${LOGO_FULL}
          <div class="logo-text-group">
            <span class="logo-text">Ithildin</span>
            <p class="subtitle">Repository Explorer</p>
          </div>
        </div>
        ${themes.length > 0 ? renderThemeSwitcher(themes, defaultTheme, assetsPath) : ''}
      </header>

      <main>
        <div id="repo-groups"></div>

        <section id="empty-state" class="empty-state" style="display:none">
          <p class="empty-state-title">No repositories found.</p>
          <p class="empty-state-desc">
            This index loads repository metadata from <code><a href="manifest.json">manifest.json</a></code>.
          </p>
          <a href="./manifest.schema.json" class="schema-link">Manifest Schema</a>
        </section>
      </main>

      ${renderFooter()}
    </div>

    <script>
      const groups = document.getElementById('repo-groups');
      const emptyState = document.getElementById('empty-state');

      function normalizeCategories(repo) {
        if (!Array.isArray(repo.categories)) return [];
        return [...new Set(
          repo.categories
            .filter((v) => typeof v === 'string')
            .map((v) => v.trim())
            .filter(Boolean)
        )];
      }

      function repoHref(repo) {
        if (typeof repo.path === 'string' && repo.path.length > 0) return repo.path;
        return './repos/' + encodeURIComponent(repo.slug) + '/index.html';
      }

      function repoLabel(repo) {
        if (typeof repo.name === 'string' && repo.name.length > 0) return repo.name;
        return repo.slug;
      }

      function compareRepos(a, b) {
        return repoLabel(a).localeCompare(repoLabel(b));
      }

      function createRepoCard(repo) {
        const item = document.createElement('li');
        item.className = 'repo-card';

        const link = document.createElement('a');
        link.href = repoHref(repo);

        const name = document.createElement('div');
        name.className = 'name';
        name.textContent = repoLabel(repo);

        const slug = document.createElement('div');
        slug.className = 'slug';
        slug.textContent = repo.slug;

        link.append(name, slug);

        if (typeof repo.description === 'string' && repo.description.length > 0) {
          const desc = document.createElement('p');
          desc.className = 'desc';
          desc.textContent = repo.description;
          link.append(desc);
        }

        if (Array.isArray(repo.tags) && repo.tags.length > 0) {
          const tags = document.createElement('div');
          tags.className = 'tags';
          for (const t of repo.tags) {
            const tag = document.createElement('span');
            tag.className = 'tag';
            tag.textContent = t;
            tags.append(tag);
          }
          link.append(tags);
        }

        item.append(link);
        return item;
      }

      function createSection(title, repositories) {
        const section = document.createElement('section');
        section.className = 'category-section';

        if (title) {
          const heading = document.createElement('h2');
          heading.className = 'category-title';
          heading.textContent = title;
          section.append(heading);
        }

        const list = document.createElement('ul');
        list.className = 'repo-grid';

        for (const repo of repositories.sort(compareRepos)) {
          list.append(createRepoCard(repo));
        }

        section.append(list);
        return section;
      }

      function showEmpty() {
        groups.replaceChildren();
        emptyState.style.display = '';
      }

      function showRepositories(repositories) {
        const valid = repositories.filter((r) => r && typeof r.slug === 'string' && r.slug.length > 0);
        if (valid.length === 0) { showEmpty(); return; }

        const categories = new Map();
        const uncategorized = [];

        for (const repo of valid) {
          const cats = normalizeCategories(repo);
          if (cats.length === 0) { uncategorized.push(repo); continue; }
          for (const cat of cats) {
            if (!categories.has(cat)) categories.set(cat, []);
            categories.get(cat).push(repo);
          }
        }

        emptyState.style.display = 'none';
        groups.replaceChildren();

        if (categories.size === 0) {
          groups.append(createSection('', valid));
          return;
        }

        for (const cat of [...categories.keys()].sort((a, b) => a.localeCompare(b))) {
          groups.append(createSection(cat, categories.get(cat)));
        }

        if (uncategorized.length > 0) {
          groups.append(createSection('Uncategorized', uncategorized));
        }
      }

      fetch('manifest.json')
        .then((r) => { if (!r.ok) throw new Error(r.status); return r.json(); })
        .then((m) => showRepositories(Array.isArray(m.repositories) ? m.repositories : []))
        .catch(() => showEmpty());
    </script>
  </body>
</html>`;
}
